### ISSUE TITLE
Upgrade path from v3.0.2 to v5.0.0 in a project using Mui.Styles

### ISSUE THREAD

**Issue by zatchheems** [cca-io/rescript-mui#212]
I have a project relies heavily on `Mui.Styles.makeStylesWithTheme`, `Mui.Styles.makeStyles`, basically everything unsupported in v5.0.0:

> NOTE: @mui/styles will never be implemented, as it is the legacy styling solution which is not compatible with React.StrictMode or React 18.

 Is there an upgrade path from v3 to v5? Is there a kludge just to get styled-components working? I understand you (the maintainer) dropped styled-components entirely. I would like not to rewrite the entirety of my app if I can avoid it.

Just wondering what my options are.

**Comment by fhammerschmidt** [comment]
I see that `@mui/styled` package more as a way to incrementally move away from JSS which is explained in the [migration guide](https://mui.com/material-ui/migration/migrating-from-jss/).

styled components are still supported for client-side-rendered apps: https://v5.mui.com/material-ui/integrations/styled-components/ so I think it is just about adding that resolution in package.json and otherwise follow the migration guide.

OR if you really want to not rewrite yet, you could just install `@mui/styles` and drop a MuiStyles.res in your repo:

```res
// MuiStyles.res
type useStyles<'a> = unit => 'a

@module("@mui/styles")
external makeStyles: {..} => useStyles<'a> = "makeStyles"

@module("@mui/styles")
external makeStylesWithTheme: (Mui.Theme.t => {..}) => useStyles<'a> = "makeStyles"
```

And then you only have to search&replace `Mui.Styles.makeStyles` with `MuiStyles.makeStyles`, at least I hope so.

**Comment by zatchheems** [comment]
ah I missed that migration guide from the Mui folks, thank you! so getting styled-components working doesn't sound like a kludge at all.

it is a large set of changes to get `@mui/styles` totally migrated over so I think I'll take their advice and gradually phase it out. thanks for those bindings!
